; NOTE: The actual debug.so extention is NOT SET HERE but rather (/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini)

xdebug.mode=debug
xdebug.start_with_request=trigger
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.log=/var/log/xdebug.log
xdebug.log_level=3
xdebug.discover_client_host=false
xdebug.idekey=VSCODE

; 性能优化设置
xdebug.max_nesting_level=250
xdebug.connect_timeout_ms=200
xdebug.start_upon_error=yes

; 调试会话设置
xdebug.remote_cookie_expire_time=3600
xdebug.client_discovery_header=HTTP_X_FORWARDED_FOR,REMOTE_ADDR

; 输出设置
xdebug.show_error_trace=0
xdebug.show_exception_trace=0
xdebug.show_local_vars=0
xdebug.var_display_max_data=512
xdebug.var_display_max_depth=3

; 性能设置
xdebug.profiler_enable=0
xdebug.output_dir="/tmp/xdebug"
